### ISSUE TITLE
Provide license

### ISSUE THREAD

**Issue by AleksandarDev** [jasonholloway/miniguid#1]
Can you please attach license to this project?

**Comment by jasonholloway** [comment]
I'll get it in place tonight - thanks for asking, it's made my day :)

**Comment by AleksandarDev** [comment]
That would be great, thanks. Love the package, but as you didn't include the license I don't know whether I can use it in my project yet... 😄

**Comment by jasonholloway** [comment]
There you go, there's a new version with MIT license now on Nuget
