### ISSUE TITLE
Why better than ShortGuid

### ISSUE THREAD

**Issue by YZahringer** [jasonholloway/miniguid#3]
ShortGuid generate smaller values (21 char), normal?
Why better?

**Comment by jasonholloway** [comment]
Yes, that's a very fair question to ask!

The answer's all about readability: ShortGuid compresses to 22 by also including numbers and two special characters ('_' and '-') - this leads to complicated-looking identifiers like `_-9g5YdI9A27c_a-2FC00ebQ2`. 

MiniGuid in comparison always outputs a blob of letters - all in the same character class, and without strange pepperings of underscores etc. It's a trade-off, I suppose - four more characters, but more regular and digestable `QxLKubVCxzzuTSKvxxizlZfyyg`

Also (not insignificantly) MiniGuid is nicely hosted on GitHub, nicely packaged with implicit conversions etc, and (drumroll) is .NET Standard compatible.

**Comment by jasonholloway** [comment]
Thanks for asking the question - I've now updated the readme!
